global:
  http:
    listenaddr: :8088

jt1078:
  enable: true
  audioports: [10000, 10010] # 音频端口 用于下发数据[min,max]
  simulations:

  realtime: # 实时视频
    addr: '0.0.0.0:10012'
    onjoinurl: "http://127.0.0.1:10011/api/v1/real-time-join"
    onleaveurl: "http://127.0.0.1:10011/api/v1/real-time-leave"
    prefix: "live/jt1078" # 默认自定义前缀-手机号-通道 如：live/jt1078-295696659617-1

  playback: # 回放视频
    addr: '0.0.0.0:10013'
    onjoinurl: "http://127.0.0.1:10011/api/v1/play-back-join"
    onleaveurl: "http://127.0.0.1:10011/api/v1/play-back-leave"
    prefix: "live/jt1079" # 默认自定义前缀-手机号-通道 如：live/jt1079-295696659617-1

mp4:
  enable: true
