name: go coverage

on:
  push

jobs:
  test:
    name: Codecov coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          cd ./protocol
          go test -coverprofile=coverage.txt ./jt808 ./model ./utils ./jt1078
          cd ../

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests # optional
          verbose: true # optional (default = false)
